### ISSUE TITLE
game validation failed: Path `waypointsLooped` is required

### ISSUE THREAD

**Issue by gileri** [mike-eason/solaris#537]
Hi, fantastic game, thank you !

When validating a turn on game `5fff50eb96b0260bff3c060b`, at least two players get the following error :

```
ValidationError: game validation failed: galaxy.carriers.11.waypointsLooped: Path `waypointsLooped` is required.
    at new ValidationError (/home/voxel/solaris/server/node_modules/mongoose/lib/error/validation.js:31:11)
    at model.Document.invalidate (/home/voxel/solaris/server/node_modules/mongoose/lib/document.js:2557:32)
    at EmbeddedDocument.invalidate (/home/voxel/solaris/server/node_modules/mongoose/lib/types/embedded.js:291:29)
    at /home/voxel/solaris/server/node_modules/mongoose/lib/document.js:2379:17
    at /home/voxel/solaris/server/node_modules/mongoose/lib/schematype.js:1173:9
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

Can we give you additional information to help debbugging ?

**Comment by mike-eason** [comment]
Hi @gileri,

Glad you're enjoying the game, shame about that issue. Can you please reload the game and see if it is fixed?

**Comment by gileri** [comment]
It is indeed fixed, thank you for the quick fix !
